#!/bin/bash

CXX=${CXX:-clang++}
SHARE=/usr/local/share/fctool

# check if the user has provided the right number of arguments
if [ $# -ne 1 ]; then
    echo "Usage: fcasmtool <cppfile>"
    exit 1
fi

NAME=${1%.cpp}

# build the source file to compile
cat $SHARE/plotarch_header.cpp > $NAME.tmp.cpp
cat $1 >> $NAME.tmp.cpp
cat $SHARE/plotarch_footer.cpp >> $NAME.tmp.cpp

# compile the source file to assembly code
$CXX -S -fverbose-asm -O3 -ffast-math -march=native -fbracket-depth=1024 -o $NAME.s $NAME.tmp.cpp
