#!/bin/bash

CXX=${CXX:-clang++}
SHARE=/usr/local/share/fctool

# check if the user has provided the right number of arguments
if [ $# -ne 2 ]; then
	echo "Usage: fccomparetool <cppfile1> <cppfile2>"
	exit 1
fi

fcplottool $1
fcplottool $2

./${1%.cpp} > ${1%.cpp}.ir
./${2%.cpp} > ${2%.cpp}.ir

diff --suppress-common-lines -y ${1%.cpp}.ir ${2%.cpp}.ir

