#!/bin/bash

CXX=${CXX:-clang++}
SHARE=/usr/local/share/fctool

# The toolkit's version, answered by fcversion beside us or on the PATH.
case ${1:-} in
    --version) "$(dirname "$0")/fcversion" "$0" 2>/dev/null || fcversion "$0"; exit $? ;;
esac

# check if the user has provided the right number of arguments
if [ $# -ne 1 ]; then
    echo "Usage: fcplottool <cppfile>"
    exit 1
fi

NAME=${1%.cpp}

# build the source file to compile
cat $SHARE/plotarch_header.cpp > $NAME.tmp.cpp
cat $1 >> $NAME.tmp.cpp
cat $SHARE/plotarch_footer.cpp >> $NAME.tmp.cpp

# compile the source file
$CXX -O3 -ffast-math -march=native -o $NAME $NAME.tmp.cpp

rm $NAME.tmp.cpp

echo $NAME

